### ISSUE TITLE
Low flow rate error

### ISSUE THREAD

**Issue by Munfred** [pachterlab/poseidon#20]
There is a known bug that we are working on fixing and that is the following: the very first time you press "Run" or "Jog +/Jog-" after you send your settings, then the speed of the motors is not accurate. A temporary workaround is to send your settings, then press "Jog +", then immediately press stop. Now if you press "Jog" or "Run" the steppers should run at the appropriate speed. Keep in mind you will have to do this after every speed change. :(

**Comment by sbooeshaghi** [comment]
This was fixed in commit 9c36cc5 made for the `arduino_serialCOM_v0.1.ino` file.
