### ISSUE TITLE
Settings never finish sending

### ISSUE THREAD

**Issue by gallagherk17** [pachterlab/poseidon#36]
I have flashed the arduino and have the gui working and it says it sends commands, however the motor does not respond to the commands.  Not sure what is going on or what the issue is.

**Comment by sbooeshaghi** [comment]
Hi @gallagherk17 can you please close this issue and make a new one following the Bug report template? This will help us better diagnose what exactly is going one. 

If you click on "New Issue" then click on "Get Started" you'll see the issue template; I just made that option available. Once you do, please close this issue.
